services:
 redis:
  image: redis:latest
  container_name: redis-service
  ports:
   - "6379:6379"
  networks:
    - amiPlatform
  healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s